Update pinned commits in test-mixin.yml

diff --git a/.github/workflows/test-mixin.yml b/.github/workflows/test-mixin.yml
--- a/.github/workflows/test-mixin.yml
+++ b/.github/workflows/test-mixin.yml
@@ -5,67 +5,46 @@ permissions:
   contents: read
 
 on:
-  # To conserve resources we only run tests against main in PRs
   pull_request:
     branches:
       - main
 
 jobs:
-  setup:
-    name: Setup tools
-    runs-on: ubuntu-latest
-    outputs:
-      cache-hit: ${{ steps.tools-cache.outputs.cache-hit }}
-    steps:
-      - name: Checkout
-        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
-        with:
-          fetch-depth: 0
-          persist-credentials: false
-      - name: Setup Go
-        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
-        with:
-          go-version: 1.23
-      - name: Tools cache
-        id: tools-cache
-        uses: actions/cache@v4
-        with:
-          path: |
-            ~/go/bin
-          key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
-      - name: Install CI dependencies
-        if: steps.tools-cache.outputs.cache-hit != 'true'
-        run: make install-ci-deps
-
   lint-mixin:
     name: Test mixin
-    needs: setup
     runs-on: ubuntu-latest
     timeout-minutes: 15
     steps:
       - name: Checkout
-        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
+        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
         with:
           fetch-depth: 0
           persist-credentials: false
+
       - name: Setup Go
         uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6
         with:
-          go-version: 1.23
+          go-version: "1.23"
+
       - name: Restore Tools cache
-        uses: actions/cache@v4
+        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
         with:
-          path: |
-            ~/go/bin
+          path: ~/go/bin
           key: ${{ runner.os }}-tools-${{ hashFiles('Makefile') }}
+
       - name: Install dependencies & build generated files
         working-directory: ./mixin
         run: make all
+
       - name: Lint jsonnet
         run: make lint-fmt
+
       - name: Lint mixin
         working-directory: ./mixin
         run: make lint
+
       - name: Check for unexpected changes in generated files
         working-directory: ./mixin
-        run: "make -B dashboards_out prometheus_alerts.yaml && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
+        run: |
+          make -B dashboards_out prometheus_alerts.yaml
+          git diff --exit-code || (echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1)
