Add 2nd generation step just in case

diff --git a/.github/workflows/test-mixin.yml b/.github/workflows/test-mixin.yml
--- a/.github/workflows/test-mixin.yml
+++ b/.github/workflows/test-mixin.yml
@@ -68,4 +68,4 @@ jobs:
         run: make lint
       - name: Check for unexpected changes in generated files
         working-directory: ./mixin
-        run: "git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
+        run: "make -B dashboards_out prometheus_alerts.yaml && git diff --exit-code || ( echo 'Error: Generated files are not up to date. Run make and commit the local diff'; exit 1; )"
